import type { Metadata } from "next"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { StickyCTA } from "@/components/sticky-cta"
import { JsonLd } from "@/components/seo/json-ld"
import { pageMetadata, siteUrl } from "@/lib/seo/site"
import { MessageCircle, Star } from "lucide-react"

export const metadata: Metadata = pageMetadata({ title: "Review Hotel Excella Vizag", description: "Share your Hotel Excella stay experience. Leave a Google review or send private feedback so our team can improve guest comfort.", path: "/review" })

const googleReviewUrl = "https://search.google.com/local/writereview?placeid=ChIJH-C8eTZbOToRDi7ckoJipcQ"

export default function ReviewPage() {
  return <div className="min-h-screen bg-background"><JsonLd data={{"@context":"https://schema.org","@type":"ReviewAction",target: googleReviewUrl,agent:{"@type":"Organization",name:"Hotel Excella",url:siteUrl}}}/><Header/><main className="pt-20"><section className="border-b border-border bg-[radial-gradient(circle_at_top,rgba(211,170,83,0.18),transparent_42%)] py-16 lg:py-24"><div className="mx-auto max-w-4xl px-4 text-center"><p className="text-sm font-semibold uppercase tracking-[0.3em] text-primary">Reviews & Reputation</p><h1 className="mt-4 font-serif text-4xl font-bold text-foreground lg:text-6xl">How was your stay at Hotel Excella?</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-muted-foreground">Your review helps future guests discover a comfortable stay near Beach Road, Tenneti Park, Kailasagiri and Rushikonda. If something needs attention, please tell us directly so our team can help.</p><div className="mt-8 flex justify-center gap-2 text-primary">{[1,2,3,4,5].map((s)=><Star key={s} className="h-8 w-8 fill-primary"/>)}</div><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><a href={googleReviewUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-6 py-3 text-sm font-bold text-primary-foreground"><Star className="h-4 w-4"/>Leave a Google Review</a><a href="https://wa.me/919985908131?text=Hello%20Hotel%20Excella%2C%20I%20would%20like%20to%20share%20feedback%20about%20my%20stay." target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 rounded-lg border border-primary/70 px-6 py-3 text-sm font-bold text-primary"><MessageCircle className="h-4 w-4"/>Send Private Feedback</a></div></div></section><section className="py-16"><div className="mx-auto grid max-w-5xl gap-6 px-4 md:grid-cols-3">{["Review CTA after stay","Clean premium review flow","Direct feedback option"].map((item)=><div key={item} className="rounded-2xl border border-border bg-card p-6 text-center"><h2 className="font-semibold text-foreground">{item}</h2><p className="mt-3 text-sm text-muted-foreground">A simple reputation journey that encourages happy guests to review and gives other guests a private support channel.</p></div>)}</div></section></main><Footer/><StickyCTA/></div>
}
