import type { Metadata } from "next"
import Link from "next/link"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { StickyCTA } from "@/components/sticky-cta"
import { ConversionCTA } from "@/components/conversion-cta"
import { JsonLd } from "@/components/seo/json-ld"
import { attractions, site } from "@/lib/seo/constants"
import { breadcrumbSchema, faqSchema, hotelSchema, organizationSchema } from "@/lib/seo/schema"

export const metadata: Metadata = { title: "Attractions near Hotel Excella | Vizag Travel Hub", description: "Explore Tenneti Park, Kailasagiri, Rushikonda Beach, TTD Temple Rushikonda, YSR View Point and Indira Gandhi Zoological Park near Hotel Excella.", alternates: { canonical: `${site.url}/attractions` }, openGraph: { title: "Attractions near Hotel Excella", description: "Master attractions guide for Hotel Excella guests in Visakhapatnam.", url: `${site.url}/attractions`, siteName: site.name, images: [{ url: site.image, width: 1200, height: 630, alt: "Hotel Excella" }], locale: "en_IN", type: "website" }, twitter: { card: "summary_large_image", title: "Attractions near Hotel Excella", description: "Vizag attractions hub for Hotel Excella guests.", images: [site.image] } }
const faqs = [{ question: "What attractions are near Hotel Excella?", answer: "Tenneti Park, Kailasagiri, Rushikonda Beach, TTD Temple Rushikonda, YSR View Point and Indira Gandhi Zoological Park are popular nearby attractions." }, { question: "Is Hotel Excella near Beach Road?", answer: "Hotel Excella is approximately 200 meters walking distance to Beach Road, with convenient access to Beach Road side attractions." }, { question: "Can I plan a one-day Vizag itinerary from Hotel Excella?", answer: "Yes. Guests can combine nearby viewpoints, parks and beaches based on available time and traffic." }]
export default function AttractionsPage() { return <div className="min-h-screen bg-background"><JsonLd data={[hotelSchema(), faqSchema(faqs), breadcrumbSchema([{ name: "Home", url: site.url }, { name: "Attractions", url: `${site.url}/attractions` }])]} /><Header /><main className="pt-20 text-foreground"><section className="border-b border-border bg-card px-4 py-16 text-center lg:py-24"><p className="text-sm font-semibold uppercase tracking-[0.35em] text-primary">Vizag Attractions Hub</p><h1 className="mx-auto mt-5 max-w-4xl font-serif text-4xl font-bold lg:text-6xl">Places to visit near Hotel Excella</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">Hotel Excella is near Beach Road and offers convenient access to popular parks, viewpoints, beaches, temples and family attractions in Visakhapatnam.</p></section><section className="px-4 py-16 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6 md:grid-cols-2 lg:grid-cols-3">{attractions.map((item) => <article key={item.slug} className="rounded-3xl border border-border bg-card p-6"><h2 className="font-serif text-2xl font-bold">{item.name}</h2><p className="mt-3 text-sm font-semibold text-primary">{item.distance} • {item.travelTime}</p><p className="mt-4 leading-7 text-muted-foreground">{item.description}</p><Link href={`/${item.slug}`} className="mt-5 inline-flex rounded-full border border-primary px-5 py-2 font-semibold text-primary">View local guide</Link></article>)}</div></section><section className="px-4 pb-12 lg:px-8"><div className="mx-auto max-w-7xl rounded-3xl border border-border bg-card p-6 md:p-8"><h2 className="font-serif text-3xl font-bold">Suggested route</h2><p className="mt-4 leading-8 text-muted-foreground">For a relaxed outing, start with Kailasagiri or Tenneti Park, return to Hotel Excella for rest, and plan Rushikonda Beach or TTD Temple Rushikonda later. Travel times are approximate and can vary by traffic.</p><Link className="mt-6 inline-flex rounded-full border border-primary px-6 py-3 font-semibold text-primary" href="/places-to-visit-near-hotel-excella">Read the detailed attractions guide</Link></div></section><ConversionCTA /></main><Footer /><StickyCTA /><div className="h-16 lg:hidden" /></div> }
