import type { Metadata } from "next"
import Link from "next/link"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { StickyCTA } from "@/components/sticky-cta"
import { ConversionCTA } from "@/components/conversion-cta"
import { JsonLd } from "@/components/seo/json-ld"
import { attractions, site } from "@/lib/seo/constants"
import { breadcrumbSchema, faqSchema, hotelSchema, organizationSchema } from "@/lib/seo/schema"

export const metadata: Metadata = { title: "Why Book Direct | Hotel Excella Visakhapatnam", description: "Book direct with Hotel Excella for direct communication, faster WhatsApp support, personalized service, flexible requests and direct assistance.", alternates: { canonical: `${site.url}/why-book-direct` }, openGraph: { title: "Why Book Direct with Hotel Excella", description: "Direct communication and faster WhatsApp support for your Hotel Excella stay.", url: `${site.url}/why-book-direct`, siteName: site.name, images: [{ url: site.image, width: 1200, height: 630, alt: "Hotel Excella" }], locale: "en_IN", type: "website" }, twitter: { card: "summary_large_image", title: "Why Book Direct", description: "Direct support for your Hotel Excella stay.", images: [site.image] } }
const faqs = [{ question: "Why should I book direct with Hotel Excella?", answer: "Booking direct gives you direct communication with the hotel team, faster WhatsApp support and clearer assistance for stay requests." }, { question: "Does Hotel Excella offer WhatsApp support?", answer: `Yes. Guests can message Hotel Excella at ${site.phonePrimary} for availability and stay assistance.` }, { question: "Can I make flexible requests directly?", answer: "Yes. Direct communication helps the team understand requests such as arrival timing, room preferences or local guidance, subject to availability and hotel policy." }]
const benefits = ["Direct communication with the hotel team", "Faster WhatsApp support", "Personalized service before arrival", "Flexible requests handled directly", "Direct assistance for local guidance"]
export default function WhyBookDirectPage() { return <div className="min-h-screen bg-background"><JsonLd data={[hotelSchema(), faqSchema(faqs), breadcrumbSchema([{ name: "Home", url: site.url }, { name: "Why Book Direct", url: `${site.url}/why-book-direct` }])]} /><Header /><main className="pt-20 text-foreground"><section className="border-b border-border bg-card px-4 py-16 text-center lg:py-24"><p className="text-sm font-semibold uppercase tracking-[0.35em] text-primary">Why Book Direct</p><h1 className="mx-auto mt-5 max-w-4xl font-serif text-4xl font-bold lg:text-6xl">Direct support for a smoother Hotel Excella stay</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">Booking direct keeps communication simple. Message or call Hotel Excella for room availability, stay questions and local assistance without unsupported pricing guarantees.</p></section><section className="px-4 py-16 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6 md:grid-cols-2 lg:grid-cols-3">{benefits.map((benefit) => <div key={benefit} className="rounded-3xl border border-border bg-card p-6"><h2 className="font-serif text-2xl font-bold">{benefit}</h2><p className="mt-4 leading-7 text-muted-foreground">Our team can help clarify your stay requirements directly and guide you toward the right room or support option.</p></div>)}</div></section><ConversionCTA title="Book direct with Hotel Excella" description="Use WhatsApp for fast room availability support or call the hotel directly." /></main><Footer /><StickyCTA /><div className="h-16 lg:hidden" /></div> }
