import type { Metadata } from "next"
import Link from "next/link"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { StickyCTA } from "@/components/sticky-cta"
import { CtaRow } from "@/components/seo/cta-row"
import { pageMetadata } from "@/lib/seo/site"
import { ConciergeBell, UtensilsCrossed, Wifi } from "lucide-react"

export const metadata: Metadata = pageMetadata({ title: "Guest Convenience Services | Hotel Excella", description: "Hotel Excella offers guest convenience services including in-room food ordering through trusted restaurant partners, WiFi details and reception assistance.", path: "/restaurants" })

export default function Page(){return <div className="min-h-screen bg-background"><Header/><main className="pt-20"><section className="border-b border-border bg-card py-16 lg:py-24"><div className="mx-auto max-w-5xl px-4 text-center"><p className="text-sm font-semibold uppercase tracking-[0.3em] text-primary">Guest Convenience Service</p><h1 className="mt-4 font-serif text-4xl font-bold text-foreground lg:text-6xl">In-Room Food Ordering</h1><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-muted-foreground">Hotel Excella does not operate a destination restaurant and this page is not a restaurant guide. In-house guests can place convenient food orders through the Guest Services Portal, with meals delivered to rooms through trusted restaurant partners.</p><div className="mt-8"><CtaRow center/></div></div></section><section className="py-16 lg:py-24"><div className="mx-auto grid max-w-7xl gap-6 px-4 md:grid-cols-3">{[{icon:UtensilsCrossed,title:"In-Room Food Ordering",text:"Convenient food ordering through our Guest Portal at hotelexcella.in/orderfood."},{icon:Wifi,title:"WiFi Details",text:"Guest Services Portal access also keeps WiFi information easy for in-house guests."},{icon:ConciergeBell,title:"Reception Assistance",text:"Contact reception for stay-related support, checkout help and quick guest assistance."}].map((item)=><article key={item.title} className="rounded-2xl border border-border bg-card p-6"><item.icon className="h-8 w-8 text-primary"/><h2 className="mt-5 text-2xl font-semibold text-foreground">{item.title}</h2><p className="mt-3 leading-7 text-muted-foreground">{item.text}</p></article>)}</div><div className="mx-auto mt-10 max-w-3xl rounded-2xl border border-primary/25 bg-primary/10 p-6 text-center"><h2 className="font-serif text-2xl font-bold text-foreground">For in-house guests</h2><p className="mt-2 text-muted-foreground">Use the Guest Services Portal for in-room food ordering, WiFi details, reception assistance, checkout support and reviews.</p><Link href="/guest" className="mt-5 inline-flex rounded-lg bg-primary px-5 py-3 text-sm font-bold text-primary-foreground">Open Guest Services</Link></div></section></main><Footer/><StickyCTA/></div>}
