import type { Metadata } from "next"
import Link from "next/link"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { StickyCTA } from "@/components/sticky-cta"
import { ConversionCTA } from "@/components/conversion-cta"
import { JsonLd } from "@/components/seo/json-ld"
import { attractions, site } from "@/lib/seo/constants"
import { breadcrumbSchema, faqSchema, hotelSchema, organizationSchema } from "@/lib/seo/schema"

export const metadata: Metadata = { title: "Dining Options near Hotel Excella | Guest Convenience", description: "Nearby dining options for Hotel Excella guests including Kamat, Pista House, Kailash Parbat and Sivakoto's Food Magic Restaurant.", alternates: { canonical: `${site.url}/dining-options-near-hotel-excella` }, openGraph: { title: "Dining Options near Hotel Excella", description: "Guest convenience guide to nearby dining options around Hotel Excella.", url: `${site.url}/dining-options-near-hotel-excella`, siteName: site.name, images: [{ url: site.image, width: 1200, height: 630, alt: "Hotel Excella" }], locale: "en_IN", type: "website" }, twitter: { card: "summary_large_image", title: "Dining Options near Hotel Excella", description: "Nearby dining options for guest convenience.", images: [site.image] } }
const diningOptions = [{ name: "Kamat", cuisine: "South Indian / vegetarian", distance: "Approx. 2–3 km", description: "A practical option for guests looking for familiar vegetarian meals and South Indian choices." }, { name: "Pista House", cuisine: "Biryani, Indian and bakery items", distance: "Approx. 3–4 km", description: "Useful for guests who prefer biryani, snacks and popular Indian dining options." }, { name: "Kailash Parbat", cuisine: "North Indian, chaat and vegetarian", distance: "Approx. 4–5 km", description: "A convenient vegetarian dining option for families and groups exploring the city." }, { name: "Sivakoto's Food Magic Restaurant", cuisine: "Indian multi-cuisine", distance: "Approx. 2–4 km", description: "A nearby restaurant option for guests seeking a broader Indian menu." }]
const faqs = [{ question: "Does this page mean Hotel Excella is a restaurant?", answer: "No. Hotel Excella is positioned as a hotel. This page lists nearby dining options for guest convenience." }, { question: "Are distances exact?", answer: "Distances are approximate and can vary based on route and traffic." }, { question: "Can in-house guests order food?", answer: "In-house guests can use available guest convenience flows, but Hotel Excella is not positioned as a restaurant business." }]
export default function DiningOptionsPage() { return <div className="min-h-screen bg-background"><JsonLd data={[hotelSchema(), faqSchema(faqs), breadcrumbSchema([{ name: "Home", url: site.url }, { name: "Dining Options", url: `${site.url}/dining-options-near-hotel-excella` }])]} /><Header /><main className="pt-20 text-foreground"><section className="border-b border-border bg-card px-4 py-16 text-center lg:py-24"><p className="text-sm font-semibold uppercase tracking-[0.35em] text-primary">Guest Convenience</p><h1 className="mx-auto mt-5 max-w-4xl font-serif text-4xl font-bold lg:text-6xl">Dining options near Hotel Excella</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">A simple local guide for guests who want nearby dining choices during their stay. Hotel Excella is a hotel, and these are nearby external options for convenience.</p></section><section className="px-4 py-16 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6 md:grid-cols-2">{diningOptions.map((item) => <article key={item.name} className="rounded-3xl border border-border bg-card p-6"><h2 className="font-serif text-2xl font-bold">{item.name}</h2><p className="mt-3 text-sm font-semibold text-primary">{item.cuisine} • {item.distance}</p><p className="mt-4 leading-7 text-muted-foreground">{item.description}</p></article>)}</div></section><ConversionCTA title="Need stay assistance?" description="Contact Hotel Excella directly for room availability and guest support." /></main><Footer /><StickyCTA /><div className="h-16 lg:hidden" /></div> }
